# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'act_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_act_4(object):
    def setupUi(self, act_4):
        act_4.setObjectName("act_4")
        act_4.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(act_4)
        self.centralwidget.setObjectName("centralwidget")
        self.analizar = QtWidgets.QPushButton(self.centralwidget)
        self.analizar.setGeometry(QtCore.QRect(200, 330, 93, 28))
        self.analizar.setObjectName("analizar")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(290, 110, 121, 16))
        self.name.setObjectName("name")
        self.texto = QtWidgets.QLabel(self.centralwidget)
        self.texto.setGeometry(QtCore.QRect(290, 180, 91, 16))
        self.texto.setObjectName("texto")
        self.line = QtWidgets.QLabel(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 250, 171, 16))
        self.line.setObjectName("line")
        self.t_name = QtWidgets.QLineEdit(self.centralwidget)
        self.t_name.setGeometry(QtCore.QRect(100, 110, 113, 22))
        self.t_name.setObjectName("t_name")
        self.t_texto = QtWidgets.QLineEdit(self.centralwidget)
        self.t_texto.setGeometry(QtCore.QRect(100, 180, 113, 22))
        self.t_texto.setObjectName("t_texto")
        self.t_line = QtWidgets.QLineEdit(self.centralwidget)
        self.t_line.setGeometry(QtCore.QRect(100, 250, 113, 22))
        self.t_line.setObjectName("t_line")
        self.t_nvocales = QtWidgets.QLineEdit(self.centralwidget)
        self.t_nvocales.setGeometry(QtCore.QRect(70, 450, 113, 22))
        self.t_nvocales.setObjectName("t_nvocales")
        self.t_nconsonantes = QtWidgets.QLineEdit(self.centralwidget)
        self.t_nconsonantes.setGeometry(QtCore.QRect(310, 450, 113, 22))
        self.t_nconsonantes.setObjectName("t_nconsonantes")
        self.nvocales = QtWidgets.QLabel(self.centralwidget)
        self.nvocales.setGeometry(QtCore.QRect(70, 410, 121, 16))
        self.nvocales.setObjectName("nvocales")
        self.nconsonantes = QtWidgets.QLabel(self.centralwidget)
        self.nconsonantes.setGeometry(QtCore.QRect(290, 410, 141, 20))
        self.nconsonantes.setObjectName("nconsonantes")
        act_4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(act_4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        act_4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(act_4)
        self.statusbar.setObjectName("statusbar")
        act_4.setStatusBar(self.statusbar)

        self.retranslateUi(act_4)
        QtCore.QMetaObject.connectSlotsByName(act_4)

    def retranslateUi(self, act_4):
        _translate = QtCore.QCoreApplication.translate
        act_4.setWindowTitle(_translate("act_4", "MainWindow"))
        self.analizar.setText(_translate("act_4", "Analizar"))
        self.name.setText(_translate("act_4", "Nombre del archivo"))
        self.texto.setText(_translate("act_4", "Texto a escribir"))
        self.line.setText(_translate("act_4", "Número de líneas en archivo"))
        self.nvocales.setText(_translate("act_4", "Número de vocales"))
        self.nconsonantes.setText(_translate("act_4", "Número de consonantes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    act_4 = QtWidgets.QMainWindow()
    ui = Ui_act_4()
    ui.setupUi(act_4)
    act_4.show()
    sys.exit(app.exec_())


